### ISSUE TITLE
cra2 requires explicit addition of sass

### ISSUE THREAD

**Issue by dfee** [couds/react-bulma-components#115]
create-react-app 2.x requires the explicit addition of sass files. I put together a minimal repository here: https://github.com/dfee/dummy-rbc

The only changes I have made after `npx create-react-app dummy` are:
1) installing `node-sass`, `github:couds/react-bulma-components`
2) adding `styles.sass` with `@import '~react-bulma-components/src/index`
3) importing `styles.sass` and `{ Button } from `react-bulma-components` in `App.tsx`
4) creating a `<Button color='info'>i am button</Button>` in `App.tsx`.

If you are to clone and download the app you will see that if you toggle the commented out line in `styles.sass` of `@import '~react-bulma-components/src/components/button/button.sass` you get the button's sass. Though, it seems from https://github.com/couds/react-bulma-components/blob/3b13b738b0bfd0bc82104b6913d3ba1367a6196a/src/components/button/index.js#L1 that shouldn't require any additional effort.

**Comment by bobman38** [comment]
Hello

Linked with #96 ?

I am just stuck in kind'a same issue with release 2.0.3 available on npm repo, so testing ``npm install couds/react-bulma-components`` and seems better for me...

**Comment by couds** [comment]
This is now solved in V3, See docs [here](https://github.com/couds/react-bulma-components#cra)

**Comment by dscottboggs** [comment]
I ran into this error, and following the docs didn't solve the problem, however, setting `NODE_PATH` to `NODE_PATH=./node_modules/react-bulma-components/src` does seem to help. I'll need to experment further, perhaps the docs need updated? Or perhaps this solution has unexpected side effects?

**Comment by couds** [comment]
Hi, did you create the _variables.sass file on your src folder? (See advanced setup)

**Comment by dscottboggs** [comment]
This was definitely my error, I hadn't added the import to my main CSS file. :man_facepalming: sorry to bother you.
