### ISSUE TITLE
Burger button not working

### ISSUE THREAD

**Issue by KenyStev** [couds/react-bulma-components#203]
https://couds.github.io/react-bulma-components/?selectedKind=Navbar&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

I found the issue and fixed in my side, it's not an issue in the source code of the library but in the story example.

the issue is `active` is supposed to be passed through the Context (as props in the Navbar component) but instead in the Story it's been passed as prop to the `Navbar.Burger` Component

*Note: I'd like to fix it if you lead me towards the documetation's source code

**Comment by MrCreeper1008** [comment]
I thnk this is fixed in v3’s documentation but i need @couds to confirm.

**Comment by couds** [comment]
Hi @KenyStev I think this issue was because the mismatch of the versions, the storybook was pointing to V2 and the burguer using the context is V3. now I updated the storybook and should work correctly.

Thanks! =)

**Comment by ivoba** [comment]
I guess its still not working, see in Chrome with responsive inspector on:
https://couds.github.io/react-bulma-components/iframe.html?id=navbar--default&viewMode=story#

The Burger menu shows up but no dropdown.

**Comment by ivoba** [comment]
You have to add the toggle mechanism yourself:

```
class MenuNavbar extends Component {

  state = { active : false }

  handleClick = () => {
    const { active } = this.state;
    this.setState({ active: !active });
  }
  render() {
    return (
      <Navbar active={this.state.active} onClick={this.handleClick}>
     .....
```
